# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core


pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  workingDirectory: WorkoutApp.API/
  displayName: 'dotnet build $(buildConfiguration)'

# - task: DotNetCoreCLI@2
#   inputs:
#     workingDirectory: WorkoutApp.API/
#     command: publish
#     publishWebProjects: True
#     arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#     zipAfterPublish: False
