# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   workingDirectory: WorkoutApp.API/
#   displayName: 'dotnet build $(buildConfiguration)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    workingDirectory: 'WorkoutApp.API/'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'API'
    publishLocation: 'Container'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'WorkoutApp-SPA/'
  
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'WorkoutApp-SPA/'
    customCommand: 'ng build -prod --base-href \"/WorkoutApp/\"'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
    ArtifactName: 'SPA'
    publishLocation: 'Container'